export const gammaExample = [
  "Arri log c",
  "Blackmagic BMD Film",
  "Blackmagic BMD Film 4K",
  "Canon Cinestyle",
  "DJI D-log",
  "Gopro Protune",
  "Other",
  "Panasonic Cinelike-D",
  "Panasonic V-log",
  "RED Color",
  "RED Log Film",
  "Rec 709",
  "Sony S-Log",
  "Sony S-Log 2",
  "Sony S-Log 3",
  "linear",
  "Panasonic V-log L",
  "Canon C-Log",
  "Canon C-Log 2",
  "Canon C-Log 3",
];
export const styleExample = [
  "2 Strip",
  "3 Strip",
  "Adventure",
  "Black and white",
  "Bleach bypass",
  "Blockbuster",
  "Blue shadows",
  "Colorful",
  "Cross Process",
  "Faded",
  "Film emulation",
  "High contrast",
  "Hipster",
  "Horror / Dark",
  "Noir",
  "Protect Shadows",
  "Protect highlights",
  "Retro",
  "Teal - Orange",
  "Vintage",
  "Warm shadows",
  "Overcast Day",
  "Golden Highlights",
  "fresh",
  "Correction",
  "Teal",
  "color change",
  "Drama",
  "Interview",
  "green shadow",
  "Cinematic light",
  "FRESH",
  "Dusty Light",
  "Ultra Blue Hour Tone",
  "2010 Films",
  "cine drama",
  "WeddingAQUA",
  "NEUTRAL",
  "Fresh look",
  "sun dwon",
  "Cinematic/Dark",
  "rainish style",
  "cool rain",
  "Interior",
];
export const colorExample = [
  "Red",
  "Blue",
  "Warm",
  "Cool",
  "Green",
  "Purple",
  "Yellow",
  "Teal",
  "Orange",
  "Black and white",
  "Magenta",
  "Brown",
  "None",
];
